{% set name = "yaehmop" %}
{% set version = "2019.03.1" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/greglandrum/yaehmop.git
  sha256: c93cd0ec1905b273e390fdea81848d0ef808a25021b27f8e053b36c23616a0bf

build:
  number: 0
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - blas 1.1 {{ variant }}
    - openblas
  run:
    - blas 1.1 {{ variant }}
    - openblas

test:
  commands:
    - eht_bind -v

about:
  home: https://github.com/greglandrum/yaehmop
  license: BSD-2-Clause
  license_family: BSD
  license_file: license.txt
  summary: 'Yet Another extended Hueckel Molecular Orbital Package'
  doc_url: https://github.com/greglandrum/yaehmop/blob/master/docs/bind_manual.pdf
  dev_url: https://github.com/greglandrum/yaehmop
  
extra:
  recipe-maintainers:
    - richardjgowers
    - micaela-matta
    - greglandrum
