appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mg9KtSIH0aYcwH7OGrDXwVmcHxkLU0wmfW8m0f0mHwgGUQAo3Rc/oRM+PST2v278XQtaNRBmNUgUhOQaCjtM+vVilT0XSms0N2OIoME3QvU7trqGVbDcxnw7HiLx9wPizzu31plFzyFRqbt/hH3mpuwRC/qrsJI+QeHTUZiaFrdmZe1pISVf4msYzzRbCKy1bmscSiuiYTDTQ8wzqiRzF1iDD/Ujhs0q3vLqqDeNoDfW0Ny+013onQVC61qUaYybGMQYm1CrZeEJOglfKAPw7KFVBKv0+XdHsU2Bq+csXL8C8GlE/QLjeFoyCXBd+XVuYhftbZ3Ok+I26aB/aziaKMz/FstNOrFpVGlAbdYFTwzWkfluPEnBoxjeH7EnJucxsoa5KoUJi5yX5nUn392+M5eGbF6B+heOTFVRgDdx8GcuYld0HLArn9APP0YOMy6Cc5wiRJBROCw5GJQo1k4AmTxZnW4tLpPSFHe0/jexqqeno+/QTSPv43euleGMLDfBAFoC23v/VNY4aCaAuT2uRfXb4IGFmYYqIxt14u3DVe7KUZ+/XDEWh/taKYByr7eFQEs0sTgzhbC1rD9EA2ME2oXWoWS42FHNvGPLWnDQcZ2xodb1IDSWtK2OpweDsGIsqYafoInGRBQk3ickou9Vx11rqhSgLFZmI9MF0UUhWL4=}
conda_forge_output_validation: true
